### PR TITLE
fix(terraform): fix terraform module versions

### PR DESCRIPTION
**Pull request by kawo123**
# Description

- Fix Terraform module versions
- Add `default_language_version` to `.pre-commit-config.yaml`

# How has this been tested?

Tested with `terraform apply` locally.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have successfully run the E2E tests, and have included the links to the pipeline runs below
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have updated any relevant documentation to reflect my changes
- [ ] I have assigned a reviewer and messaged them

# Pipeline run links:

### CODE REVIEW

**Review by browningjp-datatonic — CHANGES_REQUESTED** [review]
hey @kawo123, thank you so much for this!

Please could you update the module versions in `terraform/README.md`?

Otherwise LGTM!

**Comment by browningjp-datatonic** [comment]
It's a fair point!

These docs were (mostly) autogenerated using [terraform-docs](https://github.com/terraform-docs/terraform-docs), which works great for reusable Terraform modules that are published to the Terraform Registry.

Since I don't think we're likely to publish the `terraform` directory as a module to the Terraform Registry, let's remove this stuff from the README (everything from `<!-- BEGIN_TF_DOCS -->` below can be cut). It will make it neater and easier to maintain.

Thanks!

**Comment by kawo123** [comment]
Done! I removed the auto-generated terraform-docs from README.

**Review by browningjp-datatonic — APPROVED** [review]
This looks great, thank you so much @kawo123 !

**Comment by browningjp-datatonic** [comment]
@Linchin I don't think we have any of this automation set up. Is this something you can help us with?

**Comment by Linchin** [comment]
> @Linchin I don't think we have any of this automation set up. Is this something you can help us with?

Yes, I merged it as I just became an admin for this repo. Let me see how to do the / lgtm and / approve thing.

**Pull request merged**
